### ISSUE TITLE
slightly confusing about which methods we can use

### ISSUE THREAD

**Issue by tgrosch91** [learn-co-curriculum/key-for-min-value#14]
I ended up solving this lab calling the #key method, which I found was different than the #keys method. I'm not sure if this was allowed but I thought you should make the distinction clearer.

**Comment by curiositypaths** [comment]
Hello @tgrosch91,

Congratulations on exploring the ruby hash methods. Ideally, the assignment should be solved without the `#key` method. We updated the list of restricted methods based on your suggestion.

As always thank you for contributing.
