### ISSUE TITLE
missing sort_by

### ISSUE THREAD

**Issue by gbs4ever** [learn-co-curriculum/key-for-min-value#16]
The read me file says dont use these ruby methods 
 #key #keys #values #min #sort  #sort_by       #min_by

however the Rspec file doesnt exclude #sort_by  and the test will pass

Thank you
sim

**Comment by sgharms** [comment]
We've added testing for this

(although thanks to monkey patching and metaprogramming catching all the clever ways of dodging this test is near impossible; on the other hand, if one can metaprogram Ruby that well, one should not be challenged by this particular lab :) )
